version: '3'
services:
  dbus:
    image: mruettgers/dbus
    restart: unless-stopped
    networks:
      backend:
    volumes:
      - dbus_run:/var/run/dbus
    logging:
      options:
        tag: dbus

volumes:
  dbus_run:

networks:
  backend:
   internal: true
